### ISSUE TITLE
Где взять эти dll?

### ISSUE THREAD

**Issue by shirinkinV** [Bim4Everyone/RevitPlugins#9]
https://github.com/Bim4Everyone/RevitPlugins/blob/227aa7fdb9d5e6093a7615a4f730c7b2ce53c8b7/ProjectProps/Common.props#L155

**Comment by dosymep** [comment]
Добрый день, это библиотека часть моего фреймворка, который я отдельно в нугет не выкладывал, но они находятся в моей платформе, которую можно скачать по этой [ссылке](https://github.com/Bim4Everyone/Bim4EveryoneSetup/releases/latest)

**Comment by shirinkinV** [comment]
Спасибо

**Comment by shirinkinV** [comment]
Но собрать так и не получается без них

**Comment by dosymep** [comment]
я даже больше скажу, DevExpress нужно покупать :)

**Comment by shirinkinV** [comment]
То есть без лицензии DevExpress плагины работать не будут? Или лицензия нужна только чтоб скачивать обновления?

**Comment by dosymep** [comment]
лицензия нужна для сборки проекта, а чтобы плагины работали достаточно скачать установщик платформы, я ссылку дал выше
